using System.Security.Cryptography;using System.Text;using System.Text.Json;using Enset.Application.Authorization;using Enset.Application.Curation;using Enset.Application.GoldProfiles;using Enset.Domain.Curation;using Enset.Domain.GoldProfiles;using Enset.Domain.Users;using Enset.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;
namespace Enset.Infrastructure.GoldProfiles;
public sealed class GoldProfileVersionService(EnsetDbContext db,ICurationService curation,IDataAccessScope scope,ICurrentUserContext user,TimeProvider clock):IGoldProfileVersionService{
 public async Task<IReadOnlyList<GoldProfileVersionDto>> GetVersions(string t,Guid id,CancellationToken ct){await Visible(t,id,ct);var rows=await db.GoldProfileVersions.AsNoTracking().Where(x=>x.EntityType==t&&x.EntityId==id).OrderByDescending(x=>x.VersionNumber).ToListAsync(ct);var names=await Names(rows.Select(x=>x.CreatedByUserId),ct);return rows.Select(x=>Map(x,names)).ToArray();}
 public async Task<GoldProfileVersionDto?> Get(string t,Guid id,Guid v,CancellationToken ct){await Visible(t,id,ct);var x=await db.GoldProfileVersions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==v&&x.EntityType==t&&x.EntityId==id,ct);return x is null?null:Map(x,await Names([x.CreatedByUserId],ct));}
 public async Task<GoldProfileVersionDto?> GetCurrent(string t,Guid id,CancellationToken ct){await Visible(t,id,ct);var x=await db.GoldProfileVersions.AsNoTracking().SingleOrDefaultAsync(x=>x.EntityType==t&&x.EntityId==id&&x.IsCurrent,ct);return x is null?null:Map(x,await Names([x.CreatedByUserId],ct));}
 public async Task<GoldProfileVersionDto> Create(string t,Guid id,CancellationToken ct){await Visible(t,id,ct);object profile=t=="Building"?(object?)(await curation.GetBuildingProfileAsync(id,ct))!:(await curation.GetMeteringPointProfileAsync(id,ct))!;if(profile is null)throw new CurationNotFoundException("Gold-Profil nicht gefunden.");var json=JsonSerializer.Serialize(profile,new JsonSerializerOptions{PropertyNamingPolicy=JsonNamingPolicy.CamelCase});var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(json))).ToLowerInvariant();var current=await db.GoldProfileVersions.SingleOrDefaultAsync(x=>x.EntityType==t&&x.EntityId==id&&x.IsCurrent,ct);if(current?.SnapshotHash==hash)return Map(current,await Names([current.CreatedByUserId],ct));var now=clock.GetUtcNow().UtcDateTime;if(current is not null){current.IsCurrent=false;current.ValidToUtc=now;}var version=new GoldProfileVersion{EntityType=t,EntityId=id,ProfileType=t+"GoldProfile",VersionNumber=(current?.VersionNumber??0)+1,ValidFromUtc=now,CreatedAtUtc=now,CreatedByUserId=user.UserId??Guid.Empty,SourceCurationRevision=await db.CuratedFieldValues.LongCountAsync(x=>x.EntityType==t&&x.EntityId==id,ct),SnapshotHash=hash,SnapshotJson=json,IsCurrent=true,ReleaseStatus=GoldProfileReleaseStatus.Draft};Event(version,"Created",null,GoldProfileReleaseStatus.Draft,null);db.Add(version);await db.SaveChangesAsync(ct);return Map(version,await Names([version.CreatedByUserId],ct));}
 public Task<GoldProfileVersionDto> Release(string t,Guid id,Guid v,uint rv,string? reason,CancellationToken ct)=>Change(t,id,v,rv,GoldProfileReleaseStatus.Released,reason,ct);
 public Task<GoldProfileVersionDto> Revoke(string t,Guid id,Guid v,uint rv,string reason,CancellationToken ct)=>Change(t,id,v,rv,GoldProfileReleaseStatus.Archived,reason,ct);
 async Task<GoldProfileVersionDto> Change(string t,Guid id,Guid vid,uint rv,GoldProfileReleaseStatus status,string? reason,CancellationToken ct){if(!user.Roles.Contains(GlobalUserRole.EnsetAdmin.ToString()))throw new UnauthorizedAccessException("Nur Administratorinnen und Administratoren dürfen Gold-Profile freigeben oder widerrufen.");await Visible(t,id,ct);var x=await db.GoldProfileVersions.SingleOrDefaultAsync(x=>x.Id==vid&&x.EntityType==t&&x.EntityId==id,ct)??throw new CurationNotFoundException("Profilversion nicht gefunden.");db.Entry(x).Property(y=>y.RowVersion).OriginalValue=rv;if(status==GoldProfileReleaseStatus.Released){var ready=t=="Building"?await curation.GetBuildingReadinessAsync(id,ct):await curation.GetMeteringPointReadinessAsync(id,ct);if(ready?.IsGoldReady!=true)throw new CurationConflictException("Die Gold-Readiness ist nicht erfüllt.");var released=await db.GoldProfileVersions.Where(y=>y.EntityType==t&&y.EntityId==id&&y.ReleaseStatus==GoldProfileReleaseStatus.Released).ToListAsync(ct);foreach(var old in released){old.ReleaseStatus=GoldProfileReleaseStatus.Archived;Event(old,"Archived",GoldProfileReleaseStatus.Released,GoldProfileReleaseStatus.Archived,"Automatisch archiviert: durch neue freigegebene Version ersetzt.");}}var previous=x.ReleaseStatus;x.ReleaseStatus=status;x.ReleaseReason=reason;Event(x,status.ToString(),previous,status,reason);await db.SaveChangesAsync(ct);return Map(x,await Names([x.CreatedByUserId],ct));}
 void Event(GoldProfileVersion x,string type,GoldProfileReleaseStatus? prev,GoldProfileReleaseStatus next,string? reason)=>x.Events.Add(new(){OccurredAtUtc=clock.GetUtcNow().UtcDateTime,UserId=user.UserId??Guid.Empty,EventType=type,PreviousStatus=prev,NewStatus=next,Reason=reason,SnapshotHash=x.SnapshotHash});
 async Task Visible(string t,Guid id,CancellationToken ct){var ok=t=="Building"?await scope.CanReadBuilding(id,ct):t=="MeteringPoint"&&await scope.CanReadMeter(id,ct);if(!ok)throw new CurationNotFoundException("Objekt nicht gefunden.");}
 async Task<IReadOnlyDictionary<Guid,string>> Names(IEnumerable<Guid> ids,CancellationToken ct){var set=ids.Distinct().ToArray();return await db.ApplicationUsers.AsNoTracking().Where(x=>set.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.DisplayName,ct);}
 static GoldProfileVersionDto Map(GoldProfileVersion x,IReadOnlyDictionary<Guid,string> names)=>new(x.Id,x.EntityType,x.EntityId,x.VersionNumber,x.ProfileType,x.ValidFromUtc,x.ValidToUtc,x.CreatedAtUtc,x.CreatedByUserId,x.SourceCurationRevision,x.SnapshotHash,x.IsCurrent,x.ReleaseStatus,x.ReleaseReason,x.RowVersion,x.SnapshotJson){CreatedByDisplayName=names.GetValueOrDefault(x.CreatedByUserId,"Unbekannt")};
}
public sealed class DataProductReadinessService(IGoldProfileVersionService versions,TimeProvider clock):IDataProductReadinessService{
 public async Task<IReadOnlyList<DataProductReadinessResult>> EvaluateAll(string s,Guid id,CancellationToken ct){var list=new List<DataProductReadinessResult>();foreach(var t in Enum.GetValues<DataProductType>())list.Add(await Evaluate(t,s,id,ct));return list;}
 public async Task<DataProductReadinessResult> Evaluate(DataProductType type,string scope,Guid id,CancellationToken ct){var entity=scope=="MeteringPoint"?"MeteringPoint":"Building";GoldProfileVersionDto? profile;try{profile=(await versions.GetVersions(entity,id,ct)).FirstOrDefault(x=>x.ReleaseStatus==GoldProfileReleaseStatus.Released);}catch{throw;}var req=Requirements(type,profile);var total=req.Sum(x=>x.Weight);var percentage=total==0?0:req.Where(x=>x.Fulfilled).Sum(x=>x.Weight)*100/total;var blocking=req.Where(x=>!x.Fulfilled&&x.IsBlocking).ToList();var missing=req.Where(x=>!x.Fulfilled).ToList();var status=blocking.Count>0?DataProductReadinessStatus.NotReady:percentage==100?DataProductReadinessStatus.Ready:percentage>=80?DataProductReadinessStatus.ReadyWithWarnings:DataProductReadinessStatus.PartiallyReady;return new(type,scope,id,percentage,status,DataMaturityLevel.Gold,clock.GetUtcNow().UtcDateTime,req.Where(x=>x.Fulfilled).ToList(),missing,blocking,profile is null?["Keine freigegebene Gold-Profil-Version."]:[],profile is null?[]:[new(profile.ProfileType,profile.VersionNumber,profile.Id)],profile is null?"Keine freigegebenen Profildaten.":"Bewertung aus freigegebener Profilversion.");}
 static List<RequirementResult> Requirements(DataProductType t,GoldProfileVersionDto? p){bool has=p is not null;var r=new List<RequirementResult>{R("RELEASED_PROFILE","Freigegebenes Gold-Profil",25,true,has,"Gold-Profil erstellen und freigeben.")};if(t==DataProductType.BuildingBenchmark||t==DataProductType.EnergyBenchmark){r.Add(R("USAGE","Nutzungsart",15,true,has,"Nutzungsart kuratieren."));r.Add(R("HEATED_AREA","Beheizte Fläche",15,true,has,"Beheizte Fläche ergänzen."));r.Add(R("POSTAL_CODE","Region",10,false,has,"Postleitzahl ergänzen."));r.Add(R("HWB","HWB",8,false,false,"HWB ergänzen."));r.Add(R("CONSUMPTION","Stromverbrauch",17,true,has,"Verbrauchszeitraum kuratieren."));r.Add(R("BUILDING_STATE","Gebäudezustand",10,true,has,"Gebäudezustand festlegen."));}
 else{r.Add(R("USAGE","Nutzungsart",10,true,has,"Nutzungsart kuratieren."));r.Add(R("ENERGY_CARRIER","Energieträger",10,true,has,"Energieträger bestätigen."));r.Add(R("TIME_SERIES","Messzeitraum und Intervall",20,true,has,"Lastprofil vervollständigen."));r.Add(R("COMPLETENESS","Profilvollständigkeit",15,true,has,"Fehlende Intervalle klären."));if(t==DataProductType.EegMatching||t==DataProductType.PeerToPeerAnalysis){r.Add(R("TRANSFORMER","Transformator",10,true,false,"Netzmodell ergänzen."));r.Add(R("GRID_LEVEL","Netzebene",10,true,false,"Netzebene ergänzen."));r.Add(R("OVERLAP_14_DAYS","14 Tage Überlappung",10,true,false,"Überlappenden Messzeitraum bereitstellen."));}if(t==DataProductType.PeerToPeerAnalysis){r.Add(R("FEED_IN_TARIFF","Einspeisetarif",5,true,false,"Tarifverwaltung bereitstellen."));r.Add(R("PURCHASE_TARIFF","Bezugstarif",5,true,false,"Tarifverwaltung bereitstellen."));}}return r;}
 static RequirementResult R(string id,string name,int weight,bool block,bool ok,string guide)=>new(id,name,name,weight,block,DataMaturityLevel.Gold,ok,guide);
}
