import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router";
import { AdminPageHeader, PageState, Pagination, StatusBadge } from "../components/admin/AdminUi";
import { displayDate, displayNumber, errorMessage } from "../components/admin/adminFormat";
import "../components/admin/admin.css";
import { buildingService } from "../services/buildingService";
import type { BuildingDetail, BuildingSummary, BuildingWriteModel } from "../features/buildings/types";
import type { PagedResult } from "../types/paging";
import { BuildingForm } from "../features/buildings/BuildingForm";
import { ConfirmDialog, EntityMetadataBar, formError } from "../features/crud/crudUi";
import { EntityAuditHistory } from "../features/crud/EntityAuditHistory";
import { energySystemService } from "../services/energySystemService";
import type { EnergySystem, EnergySystemWriteModel } from "../features/energySystems/types";
import { EnergySystemForm } from "../features/energySystems/EnergySystemForm";

export function BuildingsPage() { const { buildingId } = useParams(); return buildingId ? <Detail id={buildingId} /> : <List />; }

function List() {
  const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const page=Math.max(1,Number(params.get("page"))||1);
  const [search,setSearch]=useState(params.get("search")??""); const [result,setResult]=useState<PagedResult<BuildingSummary>>(); const [error,setError]=useState(""); const [creating,setCreating]=useState(params.get("create")==="true");
  useEffect(()=>{const c=new AbortController();buildingService.list({search:params.get("search")??undefined,customerId:params.get("customerId")??undefined,isActive:params.has("isActive")?params.get("isActive")==="true":undefined,page,pageSize:50},c.signal).then(setResult).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));});return()=>c.abort();},[params,page]);
  const update=(values:Record<string,string|undefined>)=>setParams(current=>{const next=new URLSearchParams(current);Object.entries(values).forEach(([key,value])=>value?next.set(key,value):next.delete(key));return next;});
  const blank:BuildingWriteModel={buildingNumber:"",name:"",externalIdentifier:null,customerId:params.get("customerId"),grossFloorAreaM2:null,yearOfConstruction:null,latitude:null,longitude:null,rowVersion:0};
  return <section className="admin-page"><AdminPageHeader title="Gebäude" description="Gebäudestammdaten und Messdatenabdeckung"/><div className="detail-actions"><button className="primary-button" onClick={()=>setCreating(true)}>Gebäude anlegen</button></div>
    <form className="list-toolbar" onSubmit={e=>{e.preventDefault();update({search:search.trim(),page:"1"});}}><label>Suche<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={params.get("isActive")??""} onChange={e=>update({isActive:e.target.value,page:"1"})}><option value="">Alle</option><option value="true">Aktiv</option><option value="false">Inaktiv</option></select></label><button>Suchen</button></form>
    {error?<PageState>{error}</PageState>:!result?<PageState>Daten werden geladen …</PageState>:result.items.length===0?<PageState>Keine Gebäude gefunden.</PageState>:<><div className="table-wrap"><table className="admin-table"><thead><tr><th>Nummer</th><th>Name</th><th>Externe ID</th><th>Zählpunkte</th><th>Messzeitraum</th><th>Status</th><th></th></tr></thead><tbody>{result.items.map(x=><tr key={x.id}><td>{x.buildingNumber}</td><td>{x.name}</td><td>{x.externalIdentifier??"–"}</td><td>{displayNumber(x.meterCount)}</td><td>{displayDate(x.firstReadingAt)} – {displayDate(x.lastReadingAt)}</td><td><StatusBadge active={x.isActive}/></td><td><Link className="table-link" to={`/buildings/${x.id}`}>Öffnen</Link></td></tr>)}</tbody></table></div><Pagination page={result.page} totalPages={result.totalPages} onPage={p=>update({page:String(p)})}/></>}
    {creating&&<BuildingForm initial={blank} onClose={()=>setCreating(false)} onSaved={id=>navigate(`/buildings/${id}`)}/>}
  </section>;
}

function Detail({id}:{id:string}) {
  const [item,setItem]=useState<BuildingDetail>(); const [systems,setSystems]=useState<EnergySystem[]>([]); const [error,setError]=useState(""); const [editing,setEditing]=useState(false); const [audit,setAudit]=useState(false); const [confirm,setConfirm]=useState<"delete"|"restore">(); const [systemForm,setSystemForm]=useState<EnergySystem>(); const [confirmSystem,setConfirmSystem]=useState<EnergySystem>(); const [newSystem,setNewSystem]=useState(false); const [busy,setBusy]=useState(false); const [actionError,setActionError]=useState("");
  const load=useCallback(async()=>{try{const [building,allSystems]=await Promise.all([buildingService.get(id),energySystemService.list()]);setItem(building);setSystems(allSystems.items.filter(x=>x.buildingId===id));}catch(e){setError(errorMessage(e));}},[id]);
  // The callback also serves explicit reload actions after mutations.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[load]);
  if(error)return <section className="admin-page"><PageState>{error}</PageState></section>; if(!item)return <section className="admin-page"><PageState>Daten werden geladen …</PageState></section>;
  const model:BuildingWriteModel={buildingNumber:item.buildingNumber,name:item.name,externalIdentifier:item.externalIdentifier,customerId:item.customers.find(x=>x.isPrimary)?.customerId??null,grossFloorAreaM2:item.grossFloorAreaM2,yearOfConstruction:item.yearOfConstruction,latitude:item.latitude,longitude:item.longitude,rowVersion:item.rowVersion};
  const blankSystem:EnergySystemWriteModel={energySystemNumber:"",name:"",type:"",buildingId:id,ratedPowerKw:null,commissionedAt:null,decommissionedAt:null,rowVersion:0};
  const mutate=async()=>{if(!confirm)return;setBusy(true);setActionError("");try{if(confirm==="delete")await buildingService.remove(id,item.rowVersion);else await buildingService.restore(id,item.rowVersion);setConfirm(undefined);await load();}catch(e){setActionError(formError(e));}finally{setBusy(false);}};
  return <section className="admin-page"><Link className="back-link" to="/buildings">← Gebäude</Link><AdminPageHeader title={item.name} description={item.buildingNumber}/><div className="detail-actions"><button className="primary-button" onClick={()=>setEditing(true)}>Bearbeiten</button><button onClick={()=>setAudit(true)}>Änderungsverlauf</button><button className={item.isDeleted?"":"danger-button"} onClick={()=>setConfirm(item.isDeleted?"restore":"delete")}>{item.isDeleted?"Wiederherstellen":"Löschen"}</button></div><EntityMetadataBar entity={item}/>
    <section className="detail-section"><h2>Stammdaten</h2><dl className="detail-grid"><div><dt>Externe ID</dt><dd>{item.externalIdentifier??"–"}</dd></div><div><dt>Bruttogrundfläche</dt><dd>{item.grossFloorAreaM2??"–"} m²</dd></div><div><dt>Baujahr</dt><dd>{item.yearOfConstruction??"–"}</dd></div><div><dt>Messdatenabdeckung</dt><dd>{displayDate(item.firstReadingAt)} – {displayDate(item.lastReadingAt)}</dd></div></dl></section>
    <section className="detail-section"><h2>Kundenzuordnung</h2>{item.customers.length===0?<PageState>Keine Kundenzuordnung.</PageState>:item.customers.map(x=><p key={x.customerId}><Link to={`/customers/${x.customerId}`}>{x.customerName}</Link> · {x.role}</p>)}</section>
    <section className="detail-section"><div className="section-heading"><h2>Zählpunkte</h2><Link className="primary-button" to={`/meters?buildingId=${id}&create=true`}>Zählpunkt hinzufügen</Link></div>{item.meters.length===0?<PageState>Keine Zählpunkte zugeordnet.</PageState>:<div className="table-wrap"><table className="admin-table"><tbody>{item.meters.map(x=><tr key={x.id}><td>{x.meterNumber}</td><td>{x.name}</td><td>{x.quantity}</td><td>{x.unit}</td><td><Link to={`/meters/${x.id}`}>Öffnen / Bearbeiten</Link></td></tr>)}</tbody></table></div>}</section>
    <section className="detail-section"><div className="section-heading"><h2>Anlagen</h2><button className="primary-button" onClick={()=>setNewSystem(true)}>Anlage hinzufügen</button></div>{systems.length===0?<PageState>Keine Anlagen zugeordnet.</PageState>:<div className="table-wrap"><table className="admin-table"><tbody>{systems.map(x=><tr key={x.id}><td>{x.energySystemNumber}</td><td>{x.name}</td><td>{x.type}</td><td>{x.ratedPowerKw??"–"} kW</td><td><StatusBadge active={x.isActive}/></td><td><button onClick={()=>setSystemForm(x)}>Öffnen / Bearbeiten</button> <button className="danger-button" onClick={()=>setConfirmSystem(x)}>{x.isDeleted?"Wiederherstellen":"Deaktivieren"}</button></td></tr>)}</tbody></table></div>}</section>
    <p><Link className="table-link" to={`/buildings/${id}/energy`}>Objektanalyse öffnen</Link></p>
    {editing&&<BuildingForm initial={model} entityId={id} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await load();}}/>}{audit&&<EntityAuditHistory entityType="Building" entityId={id} onClose={()=>setAudit(false)}/>}
    {confirm&&<ConfirmDialog title={confirm==="delete"?"Gebäude deaktivieren":"Gebäude wiederherstellen"} confirmLabel={confirm==="delete"?"Deaktivieren":"Wiederherstellen"} busy={busy} error={actionError} onConfirm={()=>void mutate()} onClose={()=>setConfirm(undefined)}><p>Das Gebäude „{item.name}“ wird {confirm==="delete"?"deaktiviert. Zugeordnete Zählpunkte und Anlagen bleiben erhalten.":"wieder aktiviert."}</p></ConfirmDialog>}
    {newSystem&&<EnergySystemForm initial={blankSystem} onClose={()=>setNewSystem(false)} onSaved={async()=>{setNewSystem(false);await load();}}/>}
    {systemForm&&<EnergySystemForm entityId={systemForm.id} initial={{energySystemNumber:systemForm.energySystemNumber,name:systemForm.name,type:systemForm.type,buildingId:id,ratedPowerKw:systemForm.ratedPowerKw,commissionedAt:systemForm.commissionedAt,decommissionedAt:systemForm.decommissionedAt,rowVersion:systemForm.rowVersion}} onClose={()=>setSystemForm(undefined)} onSaved={async()=>{setSystemForm(undefined);await load();}}/>}
    {confirmSystem&&<ConfirmDialog title={confirmSystem.isDeleted?"Anlage wiederherstellen":"Anlage deaktivieren"} confirmLabel={confirmSystem.isDeleted?"Wiederherstellen":"Deaktivieren"} busy={busy} error={actionError} onClose={()=>setConfirmSystem(undefined)} onConfirm={()=>void(async()=>{setBusy(true);setActionError("");try{if(confirmSystem.isDeleted)await energySystemService.restore(confirmSystem.id,confirmSystem.rowVersion);else await energySystemService.remove(confirmSystem.id,confirmSystem.rowVersion);setConfirmSystem(undefined);await load();}catch(e){setActionError(formError(e));}finally{setBusy(false);}})()}><p>Die Anlage „{confirmSystem.name}“ wird {confirmSystem.isDeleted?"wieder aktiviert.":"deaktiviert. Die Zuordnung zum Gebäude bleibt erhalten."}</p></ConfirmDialog>}
  </section>;
}
