import { useCallback,useEffect,useState } from "react";
import { AdminPageHeader,PageState,Pagination } from "../components/admin/AdminUi";
import { errorMessage } from "../components/admin/adminFormat";
import { curationService } from "../services/curationService";
import type { CurationStatistics,CurationTask,CurationTaskDetail,CurationTaskPage } from "../features/curation/types";
import "./CurationCenterPage.css";
const fields:Record<string,string>={BuildingCategory:"Gebäudetyp",PrimaryUseType:"Nutzungsart",Medium:"Energieträger",CustomerId:"Kundenzuordnung",BuildingId:"Objektzuordnung",HeatedAreaSquareMeters:"Beheizte Fläche",PostalCode:"Postleitzahl"};
export function CurationCenterPage(){
 const[result,setResult]=useState<CurationTaskPage>();const[statistics,setStatistics]=useState<CurationStatistics>();const[selected,setSelected]=useState<CurationTaskDetail>();const[error,setError]=useState("");const[busy,setBusy]=useState(false),[customizing,setCustomizing]=useState(false);const[value,setValue]=useState(""),[reason,setReason]=useState("");const[page,setPage]=useState(1),[entity,setEntity]=useState(""),[field,setField]=useState(""),[confidence,setConfidence]=useState("");
 const query=useCallback(()=>{const q=new URLSearchParams({status:"Open",page:String(page),pageSize:"25"});if(entity)q.set("entityType",entity);if(field)q.set("fieldName",field);if(confidence)q.set("minimumConfidence",confidence);return q;},[page,entity,field,confidence]);
 const load=useCallback(async()=>{try{const[r,s]=await Promise.all([curationService.tasks(query()),curationService.statistics()]);setResult(r);setStatistics(s);}catch(e){setError(errorMessage(e));}},[query]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[load]);
 const open=async(task:CurationTask)=>{try{setSelected(await curationService.task(task.id));setValue(task.suggestedValue);setReason("");setCustomizing(false);}catch(e){setError(errorMessage(e));}};
 const decide=async(action:"accept"|"reject"|"customize")=>{if(!selected)return;setBusy(true);setError("");try{if(action==="accept")await curationService.accept(selected.task.id);else if(action==="reject")await curationService.reject(selected.task.id,reason);else await curationService.customize(selected.task.id,value,reason);setSelected(undefined);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 return <section className="admin-page curation-page"><AdminPageHeader title="Datenprüfung" description="Offene fachliche Entscheidungen prüfen, begründen und revisionssicher festhalten"/>{error&&<p className="form-error">{error}</p>}
 <div className="curation-layout"><section><div className="section-heading"><h2>Offene Aufgaben</h2><span>{statistics?.openTasks??0}</span></div><div className="curation-filters"><select value={entity} onChange={e=>{setEntity(e.target.value);setPage(1)}}><option value="">Alle Entitäten</option><option value="Building">Gebäude</option><option value="MeteringPoint">Zählpunkte</option></select><input placeholder="Feld" value={field} onChange={e=>{setField(e.target.value);setPage(1)}}/><input type="number" min="0" max="100" placeholder="Konfidenz ab %" value={confidence} onChange={e=>{setConfidence(e.target.value);setPage(1)}}/></div>{!result?<PageState>Aufgaben werden geladen …</PageState>:result.items.length===0?<PageState>Keine offenen Kurationsaufgaben.</PageState>:<><ul className="curation-task-list">{result.items.map(task=><li key={task.id}><button onClick={()=>void open(task)} className={selected?.task.id===task.id?"is-selected":""}><span><strong>{task.entityDisplayName}</strong><small>{fields[task.fieldName]??task.fieldName} · {task.maturityLevel}</small></span><b>{task.confidencePercent} %</b></button></li>)}</ul><Pagination page={result.page} totalPages={result.totalPages} onPage={setPage}/></>}</section>
 <section className="curation-detail"><h2>Einzelprüfung</h2>{!selected?<PageState>Eine offene Aufgabe auswählen.</PageState>:<><div className="comparison"><article><small>Originalwert</small><strong>{selected.task.originalValue??"Nicht vorhanden"}</strong><span>Quelle: {selected.task.source}</span></article><article><small>Normalisierter / vorgeschlagener Wert</small><strong>{selected.task.suggestedValue}</strong><span className="confidence">{selected.task.confidencePercent} % Confidence</span></article></div><div className="reasoning"><h3>Begründung</h3><p>{selected.task.reasoning}</p><small>Regel {selected.task.ruleId} · Version {selected.task.ruleVersion} · betroffene Entität {selected.task.entityDisplayName}</small></div>{customizing&&<div className="customize-fields"><label>Manueller Wert<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Begründung<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></div>}<div className="curation-actions">{customizing?<><button onClick={()=>setCustomizing(false)}>Später entscheiden</button><button className="primary-button" disabled={busy||!value.trim()||!reason.trim()} onClick={()=>void decide("customize")}>Manuellen Wert übernehmen</button></>:<><button className="primary-button" disabled={busy} onClick={()=>void decide("accept")}>Vorschlag übernehmen</button><button disabled={busy} onClick={()=>setCustomizing(true)}>Manuell bearbeiten</button><button className="danger-button" disabled={busy||!reason.trim()} onClick={()=>void decide("reject")}>Ignorieren</button></>}</div>{selected.decisions.length>0&&<><h3>Audit-Historie</h3><ul>{selected.decisions.map(d=><li key={d.id}>{new Date(d.decidedAtUtc).toLocaleString("de-AT")} · {d.decision} · {d.reason??"ohne Begründung"} · vorher {d.originalValue??"—"} · nachher {d.newValue??"—"}</li>)}</ul></>}</>}</section></div></section>;
}
