import { useCallback,useEffect,useState } from "react";
import { AdminPageHeader,PageState,Pagination } from "../components/admin/AdminUi";
import { errorMessage } from "../components/admin/adminFormat";
import { curationService } from "../services/curationService";
import type { CurationStatistics,CurationTask,CurationTaskDetail,CurationTaskPage } from "../features/curation/types";
import "./CurationCenterPage.css";
const fields:Record<string,string>={BuildingCategory:"Gebäudetyp",PrimaryUseType:"Nutzungsart",Medium:"Energieträger",CustomerId:"Kundenzuordnung",BuildingId:"Objektzuordnung",HeatedAreaSquareMeters:"Beheizte Fläche",PostalCode:"Postleitzahl"};
export function CurationCenterPage(){
 const[result,setResult]=useState<CurationTaskPage>();const[statistics,setStatistics]=useState<CurationStatistics>();const[selected,setSelected]=useState<CurationTaskDetail>();const[error,setError]=useState("");const[busy,setBusy]=useState(false),[customizing,setCustomizing]=useState(false);const[value,setValue]=useState(""),[reason,setReason]=useState("");const[page,setPage]=useState(1),[entity,setEntity]=useState(""),[field,setField]=useState(""),[confidence,setConfidence]=useState("");
 const query=useCallback(()=>{const q=new URLSearchParams({status:"Open",page:String(page),pageSize:"25"});if(entity)q.set("entityType",entity);if(field)q.set("fieldName",field);if(confidence)q.set("minimumConfidence",confidence);return q;},[page,entity,field,confidence]);
 const load=useCallback(async()=>{try{const[r,s]=await Promise.all([curationService.tasks(query()),curationService.statistics()]);setResult(r);setStatistics(s);}catch(e){setError(errorMessage(e));}},[query]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[load]);
 const open=async(task:CurationTask)=>{try{setSelected(await curationService.task(task.id));setValue(task.suggestedValue);setReason("");setCustomizing(false);}catch(e){setError(errorMessage(e));}};
 const decide=async(action:"accept"|"reject"|"customize")=>{if(!selected)return;setBusy(true);setError("");try{if(action==="accept")await curationService.accept(selected.task.id);else if(action==="reject")await curationService.reject(selected.task.id,reason);else await curationService.customize(selected.task.id,value,reason);setSelected(undefined);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const counters=statistics?[["Gebäude ohne Nutzungsart",statistics.buildingsWithoutUsageType],["Gebäude ohne beheizte Fläche",statistics.buildingsWithoutHeatedArea],["Gebäude ohne Postleitzahl",statistics.buildingsWithoutPostalCode],["Zählpunkte ohne Nutzungsart",statistics.meteringPointsWithoutUsageType],["Zählpunkte ohne Energieträger",statistics.meteringPointsWithoutEnergyCarrier],["Unvollständige Lastprofile",statistics.meteringPointsWithIncompleteProfiles]]as const:[];
 return <section className="admin-page curation-page"><AdminPageHeader title="Datenkurationscenter" description="Feldbezogene Reife transparent von Bronze über Silver zu Gold entwickeln"/>{error&&<p className="form-error">{error}</p>}
 <section className="maturity-summary">{(["bronze","silver","gold"]as const).map(x=><article className={`maturity maturity--${x}`} key={x}><span>{x}</span><strong>{statistics?.[x]??"–"}</strong><small>{x==="bronze"?"Rohdaten":x==="silver"?"Technisch valide":"Fachlich kuratiert"}</small></article>)}</section>
 <div className="task-groups">{counters.map(([label,count])=><p key={label}><strong>{count}</strong> {label}</p>)}</div>
 <div className="curation-layout"><section><div className="section-heading"><h2>Offene Aufgaben</h2><span>{statistics?.openTasks??0}</span></div><div className="curation-filters"><select value={entity} onChange={e=>{setEntity(e.target.value);setPage(1)}}><option value="">Alle Entitäten</option><option value="Building">Gebäude</option><option value="MeteringPoint">Zählpunkte</option></select><input placeholder="Feld" value={field} onChange={e=>{setField(e.target.value);setPage(1)}}/><input type="number" min="0" max="100" placeholder="Konfidenz ab %" value={confidence} onChange={e=>{setConfidence(e.target.value);setPage(1)}}/></div>{!result?<PageState>Aufgaben werden geladen …</PageState>:result.items.length===0?<PageState>Keine offenen Kurationsaufgaben.</PageState>:<><ul className="curation-task-list">{result.items.map(task=><li key={task.id}><button onClick={()=>void open(task)} className={selected?.task.id===task.id?"is-selected":""}><span><strong>{task.entityDisplayName}</strong><small>{fields[task.fieldName]??task.fieldName} · {task.maturityLevel}</small></span><b>{task.confidencePercent} %</b></button></li>)}</ul><Pagination page={result.page} totalPages={result.totalPages} onPage={setPage}/></>}</section>
 <section className="curation-detail"><h2>Einzelprüfung</h2>{!selected?<PageState>Eine offene Aufgabe auswählen.</PageState>:<><div className="comparison"><article><small>Originaldaten</small><strong>{selected.task.originalValue??"Nicht vorhanden"}</strong><span>Reife: {selected.task.maturityLevel}</span></article><article><small>ENSET Vorschlag</small><strong>{selected.task.suggestedValue}</strong><span className="confidence">{selected.task.confidencePercent} % Konfidenz</span></article></div><div className="reasoning"><h3>Begründung</h3><p>{selected.task.reasoning}</p><small>Regel {selected.task.ruleId} · Version {selected.task.ruleVersion} · Quelle {selected.task.source}</small></div>{customizing&&<div className="customize-fields"><label>Kuratierter Wert<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Begründung<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></div>}<div className="curation-actions">{customizing?<><button onClick={()=>setCustomizing(false)}>Abbrechen</button><button className="primary-button" disabled={busy||!value.trim()} onClick={()=>void decide("customize")}>Eigenen Wert übernehmen</button></>:<><button className="primary-button" disabled={busy} onClick={()=>void decide("accept")}>Übernehmen</button><button disabled={busy} onClick={()=>setCustomizing(true)}>Bearbeiten</button><button className="danger-button" disabled={busy} onClick={()=>void decide("reject")}>Ablehnen</button></>}</div></>}</section></div></section>;
}
