import {useEffect,useState} from "react";
import {Link} from "react-router";
import {dataQualityService,type QualityDashboard} from "../services/dataQualityService";
import "../features/dataProducts/dataProducts.css";
export function DataQualityPage(){
 const[data,setData]=useState<QualityDashboard>(),[error,setError]=useState("");
 useEffect(()=>{const c=new AbortController();dataQualityService.dashboard(c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[]);
 return <main><h1>Datenqualität</h1><p>Zustand, Auswirkung und passende Workflows der vorhandenen Daten.</p>{error&&<p className="error">{error}</p>}{data&&<><section className="kpi-grid"><article className="kpi"><span>Kunden vollständig</span><strong>{data.customerCompleteness} %</strong></article><article className="kpi"><span>Objekte vollständig</span><strong>{data.buildingCompleteness} %</strong></article><article className="kpi"><span>Zählpunkte vollständig</span><strong>{data.meterCompleteness} %</strong></article><article className="kpi"><span>Offene Import Issues</span><strong>{data.openImportIssues}</strong></article><article className="kpi"><span>Offene Datenprüfungen</span><strong>{data.openDataReviews}</strong></article></section><h2>Quality Level</h2><div className="kpi-grid">{data.qualityLevels.map(x=><article className="kpi" key={x.level}><span>{x.level}</span><strong>{x.count}</strong></article>)}</div><h2>Suitability</h2><div className="table-responsive"><table><thead><tr><th>Anwendungsfall</th><th>Geeignet</th><th>Nicht geeignet</th></tr></thead><tbody>{data.suitability.map(x=><tr key={x.useCase}><td>{x.useCase}</td><td>{x.suitable}</td><td>{x.notSuitable}</td></tr>)}</tbody></table></div><h2>Qualitätsprobleme</h2><div className="table-responsive"><table><thead><tr><th>Problem</th><th>Schweregrad</th><th>Anzahl</th><th>Trend</th><th>Kunden</th><th>Objekte</th><th>Zählpunkte</th><th>Aktion</th></tr></thead><tbody>{data.metrics.map(x=><tr key={x.code}><td><strong>{x.name}</strong><br/><small>{x.description}</small></td><td>{x.severity}</td><td>{x.count}</td><td>{x.trend}</td><td>{x.affectedCustomers}</td><td>{x.affectedBuildings}</td><td>{x.affectedMeters}</td><td><Link to={x.actionUrl}>{x.action}</Link></td></tr>)}</tbody></table></div></>}</main>
}
