import { useCallback,useEffect,useState } from "react";
import { Link,useNavigate,useParams,useSearchParams } from "react-router";
import { AdminPageHeader,PageState,Pagination,StatusBadge } from "../components/admin/AdminUi";
import { displayDate,displayNumber,errorMessage } from "../components/admin/adminFormat";
import "../components/admin/admin.css";
import { meterService } from "../services/meterService";
import type { MeterDetail,MeterSummary,MeterWriteModel } from "../features/meters/types";
import type { PagedResult } from "../types/paging";
import { MeterForm } from "../features/meters/MeterForm";
import { ConfirmDialog,EntityMetadataBar,formError } from "../features/crud/crudUi";
import { EntityAuditHistory } from "../features/crud/EntityAuditHistory";
import { meterReadingService } from "../services/meterReadingService";
import type { MeterReading,MeterReadingWriteModel } from "../features/meterReadings/types";
import { MeterReadingForm } from "../features/meterReadings/MeterReadingForm";

export function MetersPage(){const{meterId}=useParams();return meterId?<Detail id={meterId}/>:<List/>;}
function List(){
 const navigate=useNavigate();const[params,setParams]=useSearchParams();const page=Math.max(1,Number(params.get("page"))||1);const[search,setSearch]=useState(params.get("search")??"");const[result,setResult]=useState<PagedResult<MeterSummary>>();const[error,setError]=useState("");const[creating,setCreating]=useState(params.get("create")==="true");
 useEffect(()=>{const c=new AbortController();meterService.list({search:params.get("search")??undefined,buildingId:params.get("buildingId")??undefined,isActive:params.has("isActive")?params.get("isActive")==="true":undefined,page,pageSize:50},c.signal).then(setResult).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));});return()=>c.abort();},[params,page]);
 const update=(values:Record<string,string|undefined>)=>setParams(current=>{const next=new URLSearchParams(current);Object.entries(values).forEach(([k,v])=>v?next.set(k,v):next.delete(k));return next;});const blank:MeterWriteModel={meterNumber:"",name:"",buildingId:params.get("buildingId")??"",medium:"",quantity:"",unit:"",direction:"",type:"",energySystemId:null,rowVersion:0};
 return <section className="admin-page"><AdminPageHeader title="Zählpunkte" description="Zählpunktstammdaten und Messwertabdeckung"/><div className="detail-actions"><button className="primary-button" onClick={()=>setCreating(true)}>Zählpunkt anlegen</button></div><form className="list-toolbar" onSubmit={e=>{e.preventDefault();update({search:search.trim(),page:"1"});}}><label>Suche<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={params.get("isActive")??""} onChange={e=>update({isActive:e.target.value,page:"1"})}><option value="">Alle</option><option value="true">Aktiv</option><option value="false">Inaktiv</option></select></label><button>Suchen</button></form>
 {error?<PageState>{error}</PageState>:!result?<PageState>Daten werden geladen …</PageState>:result.items.length===0?<PageState>Keine Zählpunkte gefunden.</PageState>:<><div className="table-wrap"><table className="admin-table"><thead><tr><th>Nummer</th><th>Name</th><th>Gebäude</th><th>Messgröße</th><th>Einheit</th><th>Messwerte</th><th>Status</th><th></th></tr></thead><tbody>{result.items.map(x=><tr key={x.id}><td>{x.meterNumber}</td><td>{x.name}</td><td>{x.buildingName??"–"}</td><td>{x.quantity}</td><td>{x.unit}</td><td>{displayNumber(x.readingCount)}</td><td><StatusBadge active={x.isActive}/></td><td><Link to={`/meters/${x.id}`}>Öffnen</Link></td></tr>)}</tbody></table></div><Pagination page={result.page} totalPages={result.totalPages} onPage={p=>update({page:String(p)})}/></>}{creating&&<MeterForm initial={blank} onClose={()=>setCreating(false)} onSaved={id=>navigate(`/meters/${id}`)}/>}</section>;
}
function Detail({id}:{id:string}){
 const[item,setItem]=useState<MeterDetail>();const[readings,setReadings]=useState<PagedResult<MeterReading>>();const[error,setError]=useState("");const[editing,setEditing]=useState(false),[audit,setAudit]=useState(false),[confirm,setConfirm]=useState<"delete"|"restore">();const[readingForm,setReadingForm]=useState<MeterReading|null>();const[confirmReading,setConfirmReading]=useState<MeterReading>();const[busy,setBusy]=useState(false),[actionError,setActionError]=useState("");const[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(1);
 const load=useCallback(async()=>{try{const[meter,values]=await Promise.all([meterService.get(id),meterReadingService.list(id,from,to,page)]);setItem(meter);setReadings(values);}catch(e){setError(errorMessage(e));}},[id,from,to,page]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();},[load]);
 if(error)return <PageState>{error}</PageState>;if(!item||!readings)return <PageState>Daten werden geladen …</PageState>;
 const model:MeterWriteModel={meterNumber:item.meterNumber,name:item.name,buildingId:item.buildingId??"",medium:item.medium,quantity:item.quantity,unit:item.unit,direction:item.direction,type:item.type,energySystemId:null,rowVersion:item.rowVersion};const blankReading:MeterReadingWriteModel={meterId:id,timestamp:new Date().toISOString(),value:0,readingType:"Manual",qualityFlag:"Valid",intervalSeconds:null,rowVersion:0,reason:null};
 const mutate=async()=>{if(!confirm)return;setBusy(true);setActionError("");try{if(confirm==="delete")await meterService.remove(id,item.rowVersion);else await meterService.restore(id,item.rowVersion);setConfirm(undefined);await load();}catch(e){setActionError(formError(e));}finally{setBusy(false);}};
 return <section className="admin-page"><Link className="back-link" to="/meters">← Zählpunkte</Link><AdminPageHeader title={item.name} description={item.meterNumber}/><div className="detail-actions"><button className="primary-button" onClick={()=>setEditing(true)}>Bearbeiten</button><button onClick={()=>setAudit(true)}>Änderungsverlauf</button><button className={item.isDeleted?"":"danger-button"} onClick={()=>setConfirm(item.isDeleted?"restore":"delete")}>{item.isDeleted?"Wiederherstellen":"Deaktivieren"}</button></div><EntityMetadataBar entity={item}/>
 <section className="detail-section"><h2>Stammdaten</h2><dl className="detail-grid"><div><dt>Gebäudezuordnung</dt><dd>{item.buildingName??"–"}</dd></div><div><dt>Energieträger</dt><dd>{item.medium}</dd></div><div><dt>Messgröße / Einheit</dt><dd>{item.quantity} / {item.unit}</dd></div><div><dt>Typ</dt><dd>{item.type}</dd></div></dl></section>
 <section className="detail-section"><div className="section-heading"><h2>Messdaten</h2><button className="primary-button" onClick={()=>setReadingForm(null)}>Messwert hinzufügen</button></div><form className="list-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);void load();}}><label>Von<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Bis<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button>Filtern</button></form>{readings.items.length===0?<PageState>Keine Messwerte vorhanden.</PageState>:<><div className="table-wrap"><table className="admin-table"><thead><tr><th>Zeitpunkt</th><th>Wert</th><th>Qualität</th><th>Herkunft</th><th></th></tr></thead><tbody>{readings.items.map(x=><tr key={x.id}><td>{displayDate(x.timestamp)}</td><td>{x.value} {item.unit}</td><td>{x.qualityFlag}</td><td>{x.dataOrigin==="Manual"?"Manuell korrigiert":x.dataOrigin}</td><td><button onClick={()=>setReadingForm(x)}>Bearbeiten</button> <button className="danger-button" onClick={()=>setConfirmReading(x)}>Löschen</button></td></tr>)}</tbody></table></div><Pagination page={readings.page} totalPages={readings.totalPages} onPage={setPage}/></>}</section>
 {editing&&<MeterForm initial={model} entityId={id} onClose={()=>setEditing(false)} onSaved={async()=>{setEditing(false);await load();}}/>}{audit&&<EntityAuditHistory entityType="MeteringPoint" entityId={id} onClose={()=>setAudit(false)}/>}
 {confirm&&<ConfirmDialog title={confirm==="delete"?"Zählpunkt deaktivieren":"Zählpunkt wiederherstellen"} confirmLabel={confirm==="delete"?"Deaktivieren":"Wiederherstellen"} busy={busy} error={actionError} onConfirm={()=>void mutate()} onClose={()=>setConfirm(undefined)}><p>Der Zählpunkt „{item.name}“ wird {confirm==="delete"?"deaktiviert. Messwerte bleiben erhalten.":"wieder aktiviert."}</p></ConfirmDialog>}
 {readingForm!==undefined&&<MeterReadingForm unit={item.unit} entityId={readingForm?.id} initial={readingForm?{meterId:id,timestamp:readingForm.timestamp,value:readingForm.value,readingType:readingForm.readingType,qualityFlag:readingForm.qualityFlag,intervalSeconds:readingForm.intervalSeconds,rowVersion:readingForm.rowVersion,reason:null}:blankReading} onClose={()=>setReadingForm(undefined)} onSaved={async()=>{setReadingForm(undefined);await load();}}/>}
 {confirmReading&&<ConfirmDialog title="Messwert löschen" confirmLabel="Löschen" busy={busy} error={actionError} onClose={()=>setConfirmReading(undefined)} onConfirm={()=>void(async()=>{setBusy(true);setActionError("");try{await meterReadingService.remove(confirmReading.id,confirmReading.rowVersion);setConfirmReading(undefined);await load();}catch(e){setActionError(formError(e));}finally{setBusy(false);}})()}><p>Der Messwert vom {displayDate(confirmReading.timestamp)} wird als gelöscht markiert. Es erfolgt keine Massenbearbeitung.</p></ConfirmDialog>}
 </section>;
}
