import { useEffect, useState, type FormEvent } from "react";
import { Link, useParams, useSearchParams } from "react-router";
import { AdminPageHeader, PageState, Pagination, StatusBadge } from "../components/admin/AdminUi";
import { displayDate, displayNumber, errorMessage } from "../components/admin/adminFormat";
import "../components/admin/admin.css";
import { meterService } from "../services/meterService";
import type { MeterDetail, MeterReadings, MeterSummary } from "../features/meters/types";
import type { PagedResult } from "../types/paging";

export function MetersPage() { const { meterId } = useParams(); return meterId ? <Detail id={meterId} /> : <List />; }

function List() {
  const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get("page")) || 1); const [search, setSearch] = useState(params.get("search") ?? ""); const [result, setResult] = useState<PagedResult<MeterSummary>>(); const [error, setError] = useState("");
  useEffect(() => { const c = new AbortController(); meterService.list({ search: params.get("search") ?? undefined, customerId: params.get("customerId") ?? undefined, buildingId: params.get("buildingId") ?? undefined, isActive: params.has("isActive") ? params.get("isActive") === "true" : undefined, page, pageSize: 50, sortBy: params.get("sortBy") ?? "meterNumber", sortDirection: params.get("sortDirection") === "desc" ? "desc" : "asc" }, c.signal).then(setResult).catch(e => { if (!c.signal.aborted) setError(errorMessage(e)); }); return () => c.abort(); }, [params, page]);
  const update = (values: Record<string, string | undefined>) => setParams(current => { const next = new URLSearchParams(current); Object.entries(values).forEach(([k, v]) => !v ? next.delete(k) : next.set(k, v)); return next; }); const submit = (e: FormEvent) => { e.preventDefault(); update({ search: search.trim() || undefined, page: "1" }); };
  return <section className="admin-page"><AdminPageHeader title="Zähler" description="Zählerstammdaten und Messwertabdeckung" /><form className="list-toolbar" onSubmit={submit}><label>Suche<input value={search} onChange={e => setSearch(e.target.value)} /></label><label>Building-ID<input value={params.get("buildingId") ?? ""} onChange={e => update({ buildingId: e.target.value.trim() || undefined, page: "1" })} /></label><label>Status<select value={params.get("isActive") ?? ""} onChange={e => update({ isActive: e.target.value || undefined, page: "1" })}><option value="">Alle</option><option value="true">Aktiv</option><option value="false">Inaktiv</option></select></label><button>Suchen</button></form>{error ? <PageState>{error}</PageState> : !result ? <PageState>Daten werden geladen …</PageState> : result.items.length === 0 ? <PageState>Keine Zähler gefunden.</PageState> : <><div className="table-wrap"><table className="admin-table"><thead><tr><th>Nummer</th><th>Name</th><th>Gebäude</th><th>Quantity</th><th>Einheit</th><th>Richtung</th><th>Typ</th><th>Messwerte</th><th>Letzter Messwert</th><th>Status</th><th></th></tr></thead><tbody>{result.items.map(x => <tr key={x.id}><td>{x.meterNumber}</td><td>{x.name}</td><td>{x.buildingName ?? "–"}</td><td>{x.quantity}</td><td>{x.unit}</td><td>{x.direction}</td><td>{x.type}</td><td>{displayNumber(x.readingCount)}</td><td>{displayDate(x.lastReadingAt)}</td><td><StatusBadge active={x.isActive} /></td><td><Link className="table-link" to={`/meters/${encodeURIComponent(x.id)}`}>Öffnen</Link></td></tr>)}</tbody></table></div><Pagination page={result.page} totalPages={result.totalPages} onPage={p => update({ page: String(p) })} /></>}</section>;
}

function Detail({ id }: { id: string }) {
  const [item, setItem] = useState<MeterDetail>(); const [readings, setReadings] = useState<MeterReadings>(); const [error, setError] = useState("");
  useEffect(() => { const c = new AbortController(); Promise.all([meterService.get(id, c.signal), meterService.getReadings(id, { aggregation: "Raw", page: 1, pageSize: 25, sortDirection: "desc" }, c.signal)]).then(([meter, values]) => { setItem(meter); setReadings(values); }).catch(e => { if (!c.signal.aborted) setError(errorMessage(e)); }); return () => c.abort(); }, [id]);
  return <section className="admin-page"><Link className="back-link" to="/meters">← Zähler</Link><AdminPageHeader title={item?.name ?? "Zählerdetail"} description={item?.meterNumber ?? ""} />{error ? <PageState>{error}</PageState> : !item || !readings ? <PageState>Daten werden geladen …</PageState> : <><dl className="detail-grid"><div><dt>Gebäude</dt><dd>{item.buildingName ?? "–"}</dd></div><div><dt>Quantity / Einheit</dt><dd>{item.quantity} / {item.unit}</dd></div><div><dt>Hersteller</dt><dd>{item.manufacturer ?? "–"} {item.model ?? ""}</dd></div><div><dt>Seriennummer</dt><dd>{item.serialNumber ?? "–"}</dd></div><div><dt>Messwerte</dt><dd>{displayNumber(item.readingCount)}</dd></div><div><dt>Verfügbar</dt><dd>{displayDate(readings.availableFrom)} – {displayDate(readings.availableTo)}</dd></div><div><dt>Letzter Wert</dt><dd>{item.latestValue ?? "–"} {item.unit}</dd></div></dl><h2>Aktuelle Rohmesswerte</h2>{!readings.raw || readings.raw.items.length === 0 ? <PageState>Keine Messwerte vorhanden.</PageState> : <div className="table-wrap"><table className="admin-table"><thead><tr><th>Zeitpunkt</th><th>Wert</th><th>Qualität</th><th>Intervall</th></tr></thead><tbody>{readings.raw.items.map(x => <tr key={x.timestamp}><td>{displayDate(x.timestamp)}</td><td>{x.value} {item.unit}</td><td>{x.quality}</td><td>{x.intervalSeconds ?? "–"}</td></tr>)}</tbody></table></div>}</>}</section>;
}
